name: nbconvert_docs
channels:
- willingcn
dependencies:
- python=3.5
- pandoc
- nbformat
- jupyter_client
- pip:
    - setuptools
    - sphinx==1.3.6
    - nbsphinx
    - jupyter-sphinx-theme
    - recommonmark
